# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 987a87c0b1cafdd1609b1fa5b811bf51babf17cd14fa93c9333a7ae727bf3488121831d8cdd360d33b11cf4342c24595a9423525e47fa8a1a27f0cc3ebafa8d9

test:
  secret_key_base: ce4cc1ffa3c298e42083f344a4636a4e1b7511357f36b110c5863adefa04cfbadc6456ba4a6b3c49477bb7f2be0ba6192a5eae0cb906e711332de8244f457687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
